### ISSUE TITLE
Allow resize -s to take a string size rather than ID

### ISSUE THREAD

**Issue by kura** [pearkes/tugboat#101]
While writing a bash completion script for Tugboat I discovered that using `tugboat resize droplet -s 1GB` fails as it expects the ID of the size from `tugboat sizes`

I'm not sure if the `--size` flag is any different but I think it would make more sense for both to support the string representation of the size. 

In terms of the bash completio it makes a lot more sense since you cannot display the Human readable string representation to the user but actually submit the ID to the command.

**Comment by petems** [comment]
Closed by #161 (New API uses string slugs)
