### ISSUE TITLE
API v2 Support

### ISSUE THREAD

**Issue by wearhere** [pearkes/tugboat#102]
Do you have plans to support Digital Ocean's v2 API? It seems impossible currently to authorize tugboat as it still requires API and client keys vs. v2's new personal access tokens.

**Comment by zlanich** [comment]
Any idea when API v2 will be implemented? DO completely disables API v1 when we invite team members because v1 doesn't support teams, so I can't invite any team members until then lol. Thanks.

**Comment by petems** [comment]
Hi @zlanich! You can see the progress here: https://github.com/pearkes/tugboat/issues/161

There's a beta release of the API 2.0 release version of the gem, you could give that a try in the mean time :+1:

**Comment by zlanich** [comment]
I will do that very soon. Thanks!

Peter Souter wrote:

**Comment by mxdpeep** [comment]
API v1 will be shutdown on November 9th 2015

**Comment by steadystatic** [comment]
Just got the email from DigitalOcean and love Tugboat so I'm sweatin' this switchover in November. Anything that folks can do to help get Tugboat down with V2?

**Comment by petems** [comment]
Fixed by #183
