### ISSUE TITLE
API v2.0 Support

### ISSUE THREAD

**Issue by petems** [pearkes/tugboat#122]
API v2.0 support using https://github.com/boats/barge

Checklist

- [x] Add Barge to Gem
- [X] Switch over previous commands to new API: (https://github.com/pearkes/tugboat/issues/161)
- [ ] ~~Add new features (IP6 etc)~~ - Descoped, will do after release. You can see the IP6 on an existing droplet!
- [ ] Cut a new release

**Comment by nickvanw** [comment]
Just wanted to stop by on behalf of DigitalOcean and say thanks for all of the hard work! 

We just put a $50 bounty on APIv2 support via BountySource: https://www.bountysource.com/issues/5386849-api-v2-0-support - let me know if you have any questions!

**Comment by petems** [comment]
@nickvanw Awesome! I meant to get the last things over the line for so we could do a feature freeze for the non API v2 stuff. I actually forgot about it til I saw this! :smile: 

I'll see what I can do in the upcoming weeks

**Comment by carmstrong** [comment]
:+1: Would love to see API v2 support! In [Deis](https://github.com/deis/deis) we're using [docl](https://github.com/nathansamson/docl) which is an awesome tool by our community member @nathansamson.

**Comment by clemenko** [comment]
I hope this is not stalled?

**Comment by petems** [comment]
I've been working on this on and off for the last 6 months. The code changes are actually fairly simple most of the time. It's moving the testing over thats the problem, as the tests are based against local json files.

I'm tempted to do a 2.0.0alpha release with no tests to the switchover and catch the big issues, then move the testing over to VCR + Webmock to save the testing. Anyone who wants to help move the various parts over, your help is appreciated! :+1:

**Comment by clemenko** [comment]
I wish I could. I have no ruby chops..

**Comment by petems** [comment]
Progress here: #161

**Comment by petems** [comment]
Fixed by #183
