### ISSUE TITLE
1.0.0 Release

### ISSUE THREAD

**Issue by petems** [pearkes/tugboat#125]
So, our plan is to get the last stragglers through the door and then see about moving to Digital Oceans API v2.0

My idea so far: 

- [x] Changelog updated with all changes since last release
- [x] Cut a release for `1.0.0`
- [x] Release gem

**Comment by petems** [comment]
1.0.0 Released! Woop woop! Been over a year since the last Rubygems release :smile:

**Comment by pearkes** [comment]
@petems You're a hero!

**Comment by blom** [comment]
@petems Awesome work!
