### ISSUE TITLE
tugboat create --help actually creates "--help" droplet

### ISSUE THREAD

**Issue by kjtanaka** [pearkes/tugboat#126]
#### Version: 
Tugboat 0.2.0
#### Issue:
I sometimes stupidly execute `tugboat create --help` which will actually create a droplet. This is obviously my bad, and I know the right command is `tugboat help create`. However, it would be nicer if it generate an error instead, because it costs money even though it's a small loss.

Thanks!

**Comment by petems** [comment]
Merged in #143
