### ISSUE TITLE
root would be a better default username

### ISSUE THREAD

**Issue by brandondrew** [pearkes/tugboat#131]
When going through the authorization setup, it asked for the ssh user, and said it would default to my local username.  Since tugboat is dedicated to Digital Ocean, and they set up (all?) VMs with just a root user, I'm not sure what the value is to defaulting to the local username.  It seems to me that root would be the desirable default in a 99% of cases.  

(Perhaps there's some feature of DO that allows you to override this so you get a superuser with a name other than `root` or a second user with `sudo` rights, but if it exists its well hidden in their admin UI.  And the number of people manually or programmatically logging in to create a second user which matches their local username will be pretty small, even though that might arguably be the best practice.)

**Comment by petems** [comment]
Good point actually, this probably makes sense. 

Want to do a PR for it? I can pick it up if not.
