### ISSUE TITLE
'fuzzy name' message shows up even when full name is used

### ISSUE THREAD

**Issue by brandondrew** [pearkes/tugboat#132]
I have a VM whose full name is "rethink".  If I issue a command for rethink I still get a message telling me I gave a fuzzy name.  Considering the README implies that "fuzzy" `==` "partial", this is confusing.  
~~~
$tugboat ssh rethink
Droplet fuzzy name provided. Finding droplet ID...done, 3346933 (rethink)
Executing SSH (rethink)...
~~~

It seems to me that it's really not all *that* useful to tell us this *even when a fuzzy (partial) name **is** being used*, but I found it quite confusing when I wasn't using a fuzzy name.  Or perhaps I'm missing something?  Perhaps there is sometimes a noticeable delay while the API responds, and a message like this is necessary in those cases?  (Perhaps those dots in the ellipsis were acting as a progress bar and I didn't notice?)

If there's a need for a message, then perhaps it could be something like 
~~~
'rethink' matching droplet ID... 3346933
~~~

The full name could be given in parentheses after the ID when it didn't match the name typed.

**Comment by petems** [comment]
@brandondrew If you know you have the exact name, you can give the command with a specified name with the -n command:

```
$ tugboat ssh -n rethink
Droplet name provided. Finding droplet ID...done, 1234 (rethink)
...
```

Without specifying a name, it assumes you want a fuzzy search.
