### ISSUE TITLE
clarification about add-key

### ISSUE THREAD

**Issue by brandondrew** [pearkes/tugboat#136]
It is probably obvious to anyone who has been using DO for a while, but for the rest of us it would be helpful if the description for `add-key` stated that it added a key to the account, rather than to a specific droplet.   (You can see my confusion appearing in issues #134 and #135.)

**Comment by petems** [comment]
@brandondrew Hmm, I don't think you can assign non-collaborator. But feel free to do a PR for it, should be an easy merge as it's just helper docs! :+1:

**Comment by petems** [comment]
Fixed in https://github.com/pearkes/tugboat/pull/157
