### ISSUE TITLE
Multiple default SSH keys (for new droplets)?

### ISSUE THREAD

**Issue by kenny-evitt** [pearkes/tugboat#142]
I'm not sure if this is possible now. If it is possible, what's the appropriate syntax for the *.tugboat* configuration file?

**Comment by edparcell** [comment]
This worked for me:
ssh-key: ['111111', '222222']

**Comment by kenny-evitt** [comment]
@petems Thanks!

@edparcell Thanks also for your (much) earlier suggestion. Sorry for not replying sooner.
