### ISSUE TITLE
API 2.0 Switchover

### ISSUE THREAD

**Issue by petems** [pearkes/tugboat#161]
Progress on Switching over to API 2.0 API:

- [x] add-key
- [x] authorize
- [x] create
- [x] destroy
- [x] destroy-image
- [x] droplets
- [x] halt
- [x] help
- [x] images
- [x] info
- [x] info-image
- [x] keys
- [x] password-reset
- [x] rebuild
- [x] regions
- [x] resize
- [x] restart
- [x] sizes
- [x] snapshot
- [x] ssh
- [x] start
- [x] verify
- [x] version
- [x] wait

**Comment by petems** [comment]
Everything seems to work from my testing, now it's just a matter of getting all the tests ported over.

**Comment by zlanich** [comment]
I'm no Ruby pro, but I tried this to try out the progress so far and I get an error. Thoughts?:

$ gem build tugboat.gemspec
$ sudo gem install tugboat-2.0.0.pre1.gem
$ tugboat

Error: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `require': cannot load such file -- tugboat (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/tugboat-1.0.0/bin/tugboat:8:in `<top (required)>'
	from /usr/bin/tugboat:23:in `load'
	from /usr/bin/tugboat:23:in `<main>'

**Comment by petems** [comment]
"This documentation is for version 1 of the DigitalOcean API. It has been deprecated and will be shutdown on Monday, November 9, 2015." Yikes, deadline coming up fast! :scream:

**Comment by mxdpeep** [comment]
yeap, 1 month left...

**Comment by FredrikWendt** [comment]
This is great progress. Is there an easy way to try this out for a non-Rubyist? I run this all in a docker container and currently run "gem install tugboat", but is there a replacement command which would install this branch instead?
Created a https://www.bountysource.com/issues/8836949-api-2-0-switchover for your efforts so far.

**Comment by edanisko** [comment]
@FredrikWendt I too am ruby-less...

https://github.com/pearkes/tugboat/blob/master/CONTRIBUTING.md explains a lot about what you are asking.  

You're going to wind up doing something similar to the following on a linux command line:

$ sudo apt-get install bundler git
$ cd ~/
$ git clone https://github.com/pearkes/tugboat.git
$ cd tugboat
$ git checkout api2_changes
$ bundle
$ bundle exec rake install #this failed for me but led me to
$ sudo gem install ~/tugboat/pkg/tugboat-2.0.0.pre3.gem

i was able to tugboat authorize and create,  tugboat ssh made an ugly fail when i tried to ssh without an id_rsa 

but I feel set that I can make the switch on nov 9 without too much pain.

**Comment by FreedomBen** [comment]
First of all, _thank you_ for your service to the community :smile: .

Do we need to swarm this and get it working with V2?  Is it just tests that we're waiting on for a release?

**Comment by petems** [comment]
Hi @freedomben, yeah it's just a matter of getting all the tests moved over to the new job fixtures, cleaning up the commits then doing an official 2.0.0 release. I should have it done before end of October, I've been doing it on and off over the last year, but the deadline has lit a fire and I'm cranking out the last bits of test code. If I don't get the tests finished, I'll release it with pending tests and add a caveat to the post install just in case. Weve had a bunch of people testing the alpha release and most of the commands seem OK 😊

**Comment by petems** [comment]
PR here: https://github.com/pearkes/tugboat/pull/178

Only 44 failing specs to go! :smile:

**Comment by petems** [comment]
Clean PR here: https://github.com/pearkes/tugboat/pull/180

Just need to figure out why the specs fail peridocially on 2.0.0, then merge soon! :+1:

**Comment by petems** [comment]
Fixed by #183
