### ISSUE TITLE
Allow specification of user data in create command

### ISSUE THREAD

**Issue by awh** [pearkes/tugboat#162]
Datacentres with metadata support allow the specification of user data which can be accessed from within the VM; this is very useful for e.g. configuring CoreOS droplets. Requires API 2.0.

**Comment by stianeikeland** [comment]
:+1:

**Comment by fadenb** [comment]
:+1:

**Comment by akshayl** [comment]
:thumbsup:

**Comment by skeenan947** [comment]
Please!!

**Comment by petems** [comment]
This will be my last feature to get ready for the 2.0.0 official release :smile:

**Comment by skeenan947** [comment]
yay!  thank you!
