### ISSUE TITLE
Image list and authorize

### ISSUE THREAD

**Issue by moltar** [pearkes/tugboat#163]
Two related issues:

1) There is no way to list public (your) images from the command. So if I need an image ID, there is no way to get it.

2) During auth, it is asking for what default image ID I want, and I have no idea where to get it.

**Comment by donpdonp** [comment]
I had the same problem with finding global images. There is a flag but its not on the short help screen.
```
$ tugboat images --global
Global Images:
14.04 x32 (id: 9801948, distro: Ubuntu)
14.04 x64 (id: 9801950, distro: Ubuntu)
...
```

**Comment by petems** [comment]
Should be better output in https://github.com/pearkes/tugboat/pull/167
