### ISSUE TITLE
Unable to bundle to run tugboat from git repo version for testing 

### ISSUE THREAD

**Issue by PhilETaylor** [pearkes/tugboat#171]
Phils-iMac:tugboat phil$ ls
    CHANGELOG.md		README.md		spec
    CHANGELOG_old.md	Rakefile		tmp
    CONTRIBUTING.md		bin			tugboat.gemspec
    Gemfile			features
    LICENSE.md		lib

    Phils-iMac:tugboat phil$ bundle
    Updating https://github.com/cucumber/cucumber.git
    fatal: ambiguous argument 'v2.0.0.beta.2': unknown revision or path not in the working tree.
    Use '--' to separate paths from revisions, like this:
    'git <command> [<revision>...] -- [<file>...]'
    Git error: command `git rev-parse v2.0.0.beta.2` in directory
    /Users/phil/.bundler/cache/git/cucumber-05ceb559025bbb6100d3da47a65ffc7cf7b638bc
    has failed.
    If this error persists you could try removing the cache directory
    '/Users/phil/.bundler/cache/git/cucumber-05ceb559025bbb6100d3da47a65ffc7cf7b638bc'

I have tried removing the whole ```/Users/phil/.bundler``` folder and trying again to no avail.

**Comment by PhilETaylor** [comment]
If I remove the line:

    gem 'cucumber', git: 'https://github.com/cucumber/cucumber.git', tag: 'v2.0.0.beta.2'

from the Gemfile then I can run the ```bundle``` command with no errors and cucumber 1.3.20 is installed

**Comment by petems** [comment]
Hi Phil! The issue is that the repos have been moved, I'll update the gemfile.

In the future you can do `bundle install --without development test`
