### ISSUE TITLE
Bad documentation string

### ISSUE THREAD

**Issue by marcosgm** [pearkes/tugboat#174]
The command 'images' describes the wrong way to get all the images: (Use `tugboat images list --global` to show all images), it should be (Use 'tugboat images -g')

$ tugboat images
Listing Your Images
(Use `tugboat images list --global` to show all images)
My Images:
No images found

$ tugboat images list
ERROR: tugboat images was called with arguments ["list"]
Usage: "tugboat images [OPTIONS]".

$ tugboat help images
Usage:
  tugboat images [OPTIONS]

Options:
  -g, [--global]  # Show global images
  -q, [--quiet]

**Comment by marcosgm** [comment]
FYI it was installed using 'gems'
$ tugboat --version
Tugboat 1.3.0

**Comment by blom** [comment]
Fixed in #173 but not released yet.

**Comment by petems** [comment]
Good catch, my fault! :+1:

**Comment by petems** [comment]
Released as 1.3.1
