### ISSUE TITLE
Support traditional `-y` for automatically confirming a destructive action.

### ISSUE THREAD

**Issue by fake-name** [pearkes/tugboat#190]
Apparently to automatically answer "yes" or "y" to `tugboat destroy` you use `-c` for some bizarre reason.

Can you please add or switch to using `-y`, like almost every other unix tool out there?

**Comment by petems** [comment]
Merged. 

On a related note, please be considerate of the fact that this is free open-source software that people work on in their own time. Snark is not appreciated :-1:
