### ISSUE TITLE
If a command that requires arguments is entered without arguments, print the help for that.

### ISSUE THREAD

**Issue by fake-name** [pearkes/tugboat#191]
Basically, `tugboat destroy` emits the basically useless `Tugboat attempted to find a droplet with no arguments. Try 'tugboat help'` message. This then leads to running `tugboat help`, which then leads to finally executing `tugboat help destroy` to get any actually usefull output.

This is kind of ridiculous. If you execute `tugboat destroy` without arguments, *print it's help*. Doing so should not break any compatibility with anything, and makes `tugboat` more useable.

**Comment by petems** [comment]
@fake-name Good idea, PR's welcome :+1:

**Comment by petems** [comment]
Fixed.

Again, please appreciate the fact that this is open-source software maintained by volunteers. Snarkiness isn't fun.

**Comment by fake-name** [comment]
I apologize, I'm rather constitutionally predisposed to sarcasm, and having spent hours fighting with strange docker issues together with droplet issues doesn't make me too genial.

I've cleaned up the report a bit.

**Comment by petems** [comment]
@fake-name hah, no worries man. It's a good point, the UX of tugboat has sometimes been a bit iffy. Hopefully these changes make things a bit better :smile:
