### ISSUE TITLE
Ipv6 changes broke ssh

### ISSUE THREAD

**Issue by mtbottle** [pearkes/tugboat#192]
It looks like the new changes to add ipv6 broke functionality to get ip's from fuzzy matching. 

The error I get is: 
```
tugboat ssh platform
Droplet fuzzy name provided. Finding droplet ID...Multiple droplets found.

1) ui-platform (123456)
2) ui-platform-staging (123457)

Please choose a droplet: ["0", "1"] 1
Executing SSH ui-platform-staging...
ssh: Could not resolve hostname : Name or service not known
```

I made a hacky change (https://github.com/mtbottle/tugboat/commit/0caa7f3772806643d09557dda2dcc463da4d5960) to fix it for my usecase. However it does not deal with someone wanting to ssh onto a machine with ipv6.

**Comment by petems** [comment]
@mtbottle That's not that hacky IMO, I'm going to PR that to fix the bug. 

I'll need to add a new flag to allow the choice to SSH to the IP6 address.
