### ISSUE TITLE
Slugs don't work

### ISSUE THREAD

**Issue by adamierymenko** [pearkes/tugboat#204]
In 2.0.0 when you try to use slugs you get things like:

    Expected numeric value for '--size'; got "16gb"

Looking at cli.rb it looks like you have ":numeric" as the type when slugs are alphanumeric strings. So slugs don't work at all.

**Comment by adamierymenko** [comment]
Editing cli.rb and changing these to ":string" seems to fix it.

**Comment by nuxlli** [comment]
Same problem here for `--region`:

```sh
Expected numeric value for '--region'; got "nyc1"
```

**Comment by petems** [comment]
Damn, I think I fixed this in a branch and forgot to merge it, will fix soon! :+1:

**Comment by petems** [comment]
Fixed and released in 2.0.1 :+1:
