### ISSUE TITLE
Seems to be a limit to the number of retrieved droplets

### ISSUE THREAD

**Issue by adamierymenko** [pearkes/tugboat#205]
Just created 200 droplets for a large scale distributed network test. They created but "tugboat droplets" doesn't list them all. There seems to be some kind of length limit. Have to log into the web UI to see them all.

**Comment by petems** [comment]
I'm afraid so, the API limits the response to 200 at a time: `The maximum number of results per page is 200.`

This could be extended to get several pages however.

**Comment by petems** [comment]
Reminder for this:

```
# Check if a response is paginated

barge.action.all.paginated? # => true
barge.region.all.paginated? # => false

# Get the previous page number

barge.image.all(per_page: 5, page: 2).prev_page # => 1

# Get the next page number

barge.image.all(per_page: 5, page: 2).next_page # => 3

# Get the last page number

barge.image.all(per_page: 5, page: 2).last_page # => 8
```

So some logic that goes "If page is paginated, get list of pages, then iteratively print responses from each page"

**Comment by lachesis** [comment]
+1 on this issue - this is a regression from the v1 API.
