### ISSUE TITLE
bug in connect

### ISSUE THREAD

**Issue by mxdpeep** [pearkes/tugboat#211]
When not entering the access token, tugboat says incorrectly:

Authentication with DigitalOcean was successful.

then it crashes:

.rvm/gems/ruby-2.2.1/gems/tugboat-2.0.1/lib/tugboat/middleware/list_droplets.rb:10:in `call': undefined method `empty?' for nil:NilClass (NoMethodError)

so I assume the authentication message is not correct at all, fixed by entering the token manually to .tugboat

**Comment by petems** [comment]
Hi @mxdpeep! Yep, looks like this was overlooked, as it used to throw a Faraday error when authentication was wrong, now it just simply returns a hash:

```ruby
[2] pry(#<Tugboat::Middleware::CheckCredentials>)> env['barge'].droplet.all
=> {"id"=>"unauthorized", "message"=>"Unable to authenticate you."}
```

I'll get a fix for this out soon!
