### ISSUE TITLE
Show private ip alongside public ip in droplets list

### ISSUE THREAD

**Issue by aeneaswiener** [pearkes/tugboat#220]
In tugboat version 2.0.1 when calling 

```
tugboat droplets
```

The output does not show the private ip for all the droplets. Is there a way to enable this?

**Comment by petems** [comment]
@aeneaswiener Yep, that was added in 9c66967ab33b42e9b01388946fb4015ff89aea9b, but I foolishly forgot to add a spec for it so there's been a regression since the switch to API 2.0!

I'll see if I can whip up a PR with fix and get a release out before the end of the week :+1:
