### ISSUE TITLE
API call to add ssh keys

### ISSUE THREAD

**Issue by vladimirghetau** [pearkes/tugboat#245]
Hello All, 

At the moment I cannot add SSH keys via the API, is this feature coming anytime soon? I see v2 of the DO api supports this here: 

https://developers.digitalocean.com/documentation/v2/#create-a-new-key

This would be great to have, it helps quite a lot with the provisioning.

Many thanks,
Vlad

**Comment by petems** [comment]
@vladimirghetau: What version of tugboat do you have? That should be avaliable as the `add-key` function!

```
~ $ tugboat help add-key
Usage:
  tugboat add-key KEY-NAME

Options:
  -k, [--key=KEY]    # The string of the key
  -p, [--path=PATH]  # The path to the ssh key
  -q, [--quiet]

Description:
  This uploads a ssh-key to DigitalOcean, which you can then assign to a droplet at creation time so you can connect to it with the key rather than a password.
```

**Comment by vladimirghetau** [comment]
Excellent! 

I am using the latest version, installed via gem, however this add-key wasn't in the README documentation. 

All good now, I tried it and it's there. Super product!

Vlad

**Comment by petems** [comment]
Thanks! Yeah, I don't think our docs have kept up with our features, I'll add that one in now 👍
