### ISSUE TITLE
This compared to doctl?

### ISSUE THREAD

**Issue by mrjcleaver** [pearkes/tugboat#251]
As Digital Ocean have an official CLI, what's the future of tugboat?

https://github.com/digitalocean/doctl

https://github.com/digitalocean/doctl/pull/70

**Comment by petems** [comment]
@mrjcleaver I was actually thinking about this recently. 

**tl;dr:** If you want the best support and the latest features, doctl is always going to be the bleeding edge. But as long as there is at least one user out there that finds Tugboat useful I will keep tinkering and maintaining 😄 

I'm going to write a longer screed and add it to the README for context, I actually hadn't worked on Tugboat for a while, but when @marrie mentioned in #248 that she prefered Tugboat over Doctl for accessibility reasons, that was a good enough reason for me to come back and start hacking.
